// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { BarArgs } from "./bar";
export type Bar = import("./bar").Bar;
export const Bar: typeof import("./bar").Bar = null as any;
utilities.lazyLoad(exports, ["Bar"], () => require("./bar"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "foo:bar:Bar":
                return new Bar(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("foo", "bar", _module)
