// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

import * as pulumiAws from "@pulumi/aws";

export class Baz extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'foo:baz:Baz';

    /**
     * Returns true if the given object is an instance of Baz.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Baz {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Baz.__pulumiType;
    }

    public readonly bucket!: pulumi.Output<pulumiAws.s3.Bucket>;
    public /*out*/ readonly bucketTwo!: pulumi.Output<pulumiAws.s3.Bucket>;

    /**
     * Create a Baz resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: BazArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.bucket === undefined) && !opts.urn) {
                throw new Error("Missing required property 'bucket'");
            }
            resourceInputs["bucket"] = args ? args.bucket : undefined;
            resourceInputs["bucketTwo"] = undefined /*out*/;
        } else {
            resourceInputs["bucket"] = undefined /*out*/;
            resourceInputs["bucketTwo"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Baz.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a Baz resource.
 */
export interface BazArgs {
    bucket: pulumi.Input<pulumiAws.s3.Bucket>;
}
