// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Foo.Bar.Inputs
{

    public sealed class NestedObjectArgs : global::Pulumi.ResourceArgs
    {
        [Input("optProp")]
        private InputList<string>? _optProp;
        public InputList<string> OptProp
        {
            get => _optProp ?? (_optProp = new InputList<string>());
            set => _optProp = value;
        }

        [Input("reqProp", required: true)]
        public Input<string> ReqProp { get; set; } = null!;

        public NestedObjectArgs()
        {
        }
        public static new NestedObjectArgs Empty => new NestedObjectArgs();
    }
}
