// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Foo.Baz
{
    [FooResourceType("foo:baz:Baz")]
    public partial class Baz : global::Pulumi.ComponentResource
    {
        [Output("bucket")]
        public Output<Pulumi.Aws.S3.Bucket> Bucket { get; private set; } = null!;

        [Output("bucketTwo")]
        public Output<Pulumi.Aws.S3.Bucket> BucketTwo { get; private set; } = null!;


        /// <summary>
        /// Create a Baz resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Baz(string name, BazArgs args, ComponentResourceOptions? options = null)
            : base("foo:baz:Baz", name, args ?? new BazArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class BazArgs : global::Pulumi.ResourceArgs
    {
        [Input("bucket", required: true)]
        public Input<Pulumi.Aws.S3.Bucket> Bucket { get; set; } = null!;

        public BazArgs()
        {
        }
        public static new BazArgs Empty => new BazArgs();
    }
}
