// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Foo.Bar
{
    [FooResourceType("foo:bar:Bar")]
    public partial class Bar : global::Pulumi.ComponentResource
    {
        [Output("bucket")]
        public Output<Pulumi.Aws.S3.Bucket> Bucket { get; private set; } = null!;

        [Output("bucketName")]
        public Output<string> BucketName { get; private set; } = null!;

        [Output("nestedObjs")]
        public Output<ImmutableArray<Outputs.NestedObject>> NestedObjs { get; private set; } = null!;


        /// <summary>
        /// Create a Bar resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Bar(string name, BarArgs args, ComponentResourceOptions? options = null)
            : base("foo:bar:Bar", name, args ?? new BarArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class BarArgs : global::Pulumi.ResourceArgs
    {
        [Input("bucketName", required: true)]
        public string BucketName { get; set; } = null!;

        [Input("nestedObjs", required: true)]
        private InputList<Inputs.NestedObjectArgs>? _nestedObjs;
        public InputList<Inputs.NestedObjectArgs> NestedObjs
        {
            get => _nestedObjs ?? (_nestedObjs = new InputList<Inputs.NestedObjectArgs>());
            set => _nestedObjs = value;
        }

        public BarArgs()
        {
        }
        public static new BarArgs Empty => new BarArgs();
    }
}
